WebBluetoothCG/web-bluetooth

- index.html
Resolves #62, making attributes unsigned.
> Make deviceClass, vendorID, productID, productVersion "unsigned long".

- index.html
This explicitly allows implementations to choose which GATT sub-procedures they
want to use to handle requests, integrates error handling into the GATT
navigation methods, and specifies that BluetoothGATT* objects are shared across
queries.
I still need to fix up:
1) the other places that specify precise GATT procedures.
2) the handling of ServiceChanged indications, which can take advantage of the explicit cache.
This is almost enough for #9: I think connection is the only imprecise algorithm left.
@marcoscaceres @scheib, let me know what you think of the demo at https://rawgit.com/jyasskin/web-bluetooth-1/information-model/index.html. I could move things around, reword, etc.
> Define a Bluetooth cache, and use it in GATT navigation.

- index.html
This also stops the spec from using overloading.
@jracle @scheib, let me know if this matches how you expected #39 to be resolved. Demo at https://rawgit.com/jyasskin/web-bluetooth-1/drop-sequence-uuid-getters/index.html.
> Fix #39: Drop the tree navigators that take a sequence of UUIDs.

- index.html
Demo at [https://rawgit.com/jyasskin/web-bluetooth-1/empty-scan-result/index.html](https://rawgit.com/jyasskin/web-bluetooth-1/empty-scan-result/index.html#widl-BluetoothDiscovery-requestDevice-Promise-BluetoothDevice--sequence-BluetoothScanFilter--filters-RequestDeviceOptions-options)
> Fix #61: Be clear that the UA must show a prompt even if no devices were found.

- index.html
I think this isn't part of the minimum viable release, but I'd like to give people an indication of what I think this access will eventually look like. Any ideas for how best to mark that?
@armansito @mmocny @marcoscaceres 
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/advertising-data/index.html.
> Add advertising data to BluetoothDevice.

- cg-summary.md
@marcoscaceres @anssiko: Here's an attempt to help people who land on https://www.w3.org/community/web-bluetooth/ find their way to the places the spec is actually developed. I also had team-community-process@w3c add the Github link to the Tools section.
Once this PR lands, with any other changes folks think are a good idea, I'll ask the W3C folks to update the CG page.
> Update the Community Group summary with github and spec links.

- index.html
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/update-bt-standard/index.html.
> Update the normative reference from Bluetooth 4.1 to 4.2.

- charter.md
* List stream communication as out-of-scope.
* Suggest that the Spec be dual-licensed.
* Mention the security model, test suite, and polyfills as extra deliverables.
* Rephrase the WebAppSec liason, since they should review more than just our use of "secure contexts".
* Mention possibly asking for changes to Bluetooth itself, through the SIG.
* Mention that contributions can come in through GitHub.
@anssiko
> Add more content to the draft Web Bluetooth CG Charter:

- use-cases.html
Uses Cases 2.1.1.: "Bicycle cadence sensor" link was broken. Changed for a functioning one. Fixes #89
> Changed broken link

- charter.md
As discussed on [CG mail list] (https://lists.w3.org/Archives/Public/public-web-bluetooth/2015Mar/0024.html), simplify the contribution rules.
> [charter] simplify Contribution Mechanics

- index.html
@g-ortuno @armansito 
I suspect we should rewrite the Introduction to be more explanatory, but this'll fix the immediate issue.
> Fix assertion that Peripherals can only receive one connection.

- charter.md
https://lists.w3.org/Archives/Public/public-web-bluetooth/2015Apr/0001.html confirmed the preference to put the archive on a list folks aren't automatically subscribed to, to avoid spam. I'll make sure this list is mentioned in the Mailing Lists on https://www.w3.org/community/web-bluetooth/.
@marcoscaceres @wcarr
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/98)
> Update the archive address for github issues, in the charter.

- index.html
Demo: https://rawgit.com/jyasskin/web-bluetooth-1/contiguous-idl/index.html
https://github.com/jyasskin/web-bluetooth-1/compare/contiguous-idl...jyasskin:wording-cleanups has a few cleanups applied. I still need to fix a couple bugs in ReSpec:
* Fix Contiguous IDL mode to link the UUID typedef.
* Figure out why definitions in notes aren't linking.
And a couple bugs in the spec that I noticed when I went over the whole text:
* writeValue needs a definition.
* Descriptor.readValue and writeValue need definitions.
* BluetoothInteraction needs promise-based methods, a store the UA looks up the IDs in, and a description of what happens when the ID isn't present.
* Say something about how `ieee_11073-20601_regulatory_certification_data_list` is mapped to an attribute name.
[<img …
> Switch to ReSpec's contiguous IDL mode.

- index.html
This changes calls like 
```javascript
requestDevice(
[ {services: [A, B]},
{services: [A, C]}],
{optionalServices: [D, E]})
```
to
```javascript
requestDevice({
filters: [ {services: [A, B]},
{services: [A, C]}],
optionalServices: [D, E]
});
```
I think it's a little clearer to label the array, but I'm happy to drop this if other people think it's worse, or that we should just put it off until we have developer feedback.
https://rawgit.com/jyasskin/web-bluetooth-1/filters-in-requestdevice-options/index.html#device-discovery
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/107)
> Move requestDevice()'s filters argument into its options dictionary.

- README.md
- implementation-status.md
Adds an Implementation Status Document that contains browser-specific
information about the current status of Web Bluetooth.
We want a page that we can point developers to when they ask to try out
the Web Bluetooth API.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/110)
> Add Implementation Status

- index.html
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/refactor-uuids/index.html#standardized-uuids.
I think this is a good way to refer to the external Bluetooth UUID registry, but I didn't find/look hard for a web spec to imitate, so let me know if there's a better way.
This currently breaks the `BluetoothServiceUUID` typedefs; I'll send a subsequent change to turn those into `DOMString`s that I explicitly pass through these new functions.
@marcoscaceres @esprehn @scheib
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/112)
> Move the navigator.bluetooth.uuids tree to methods on BluetoothUUID

- index.html
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/specify-read-write/index.html.
I also switched ArrayBuffer arguments to BufferSource per advice in
https://heycam.github.io/webidl/#idl-buffer-source-types
Fixes #26, postponing the options dictionary to the second version of the API.
Also fixes #44.
@armansito @shawnjohnjr see if this is precise enough. We may also want a new bug for adding reliable-write/transaction support in the next version.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/111)
> Specify writeValue on characteristics and both readValue and writeValue on descriptors.

- index.html
The Mac/iOS platforms don't expose a persistent instance ID for attributes. I
believe they use object identity within a process to distinguish multiple
attributes with the same UUID, although that's not documented. This patch also
documents that the web platform will use object identity for this purpose.
Removing instance IDs makes BluetoothInteraction empty, so I don't need
Bluetooth to have multiple components anymore.
Fixes #51 and fixes #52.
> Remove attribute instance IDs, and merge BluetoothDiscovery and BluetoothInteraction.

- index.html
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/rewrite-intro/index.html.
The description of the GATT hierarchy moved to the Information Model section.
Fixes #91 by describing included services in more detail.
> Rewrite the introduction to shorten it and defer more to the BT spec.

- index.html
This adds back the event handling support to navigator.bluetooth that got lost
in c40ada33c0.
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/clean-up-inheritance/index.html.
> Use 'implements' to get the event handling members, rather than inheritance.

- index.html
This allows users to add helper functions to their prototypes without getting an
object first. This spec claims the window.Bluetooth* namespace.
I've included `Bluetooth`, the type of `navigator.bluetooth`, for symmetry, even though users can just modify `navigator.bluetooth` directly.
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/expose-the-right-interfaces/index.html.
> Expose all interfaces with user-visible instances, and make sure they start with "Bluetooth".

- index.html
Issue #133 tracks applying this to the other functions taking unsigned long.
This also allows some non-integer arguments, due to WebIDL details.
https://codereview.chromium.org/1210173011/ shows the behavior.
> Enforce that canonicalUUID() is called with an in-range alias.

- index.html
The common case seems to be navigating a tree with certain attributes expected
to be there, and null checks make that more complicated. It's still possible to
handle optional attributes by catching the exception.
We have less experience with the multi-attribute getters, but I'm doing them
consistently for now.
Fixes #124.
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/throw-for-missing-attributes/index.html. @beaufortfrancois @scheib
> Throw NotFoundError when trying to look up a non-existent attribute.

- index.html
- rationale.md
instead of silently returning no devices.
Fixes #142.
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/loud-empty-filters/index.html. @beaufortfrancois @scheib
> Throw an exception if requestDevice() filters include no services

- index.html
This avoids questions about how to capitalize "ID". There aren't any other uses
of instanceID left, since #113 removed them, so we don't need this spelling to
be consistent.
Fixes #139.
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/rename-instanceid/index.html.
> Rename BluetoothDevice.instanceID to BluetoothDevice.id.

- index.html
Fixes #24.
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/blacklists/index.html. The registry PR is at https://github.com/WebBluetoothCG/registries/pull/1. @scheib @marcoscaceres
> Add the GATT blacklist.

- index.html
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/unify-uuid-algorithms/index.html#standardized-uuids
> Unify the BluetoothUUID.get* algorithms.

- tests/index.bs
- tests/index.html
This matches the current Chromium test APIs (eventSender.keyDown and
testRunner.setBluetoothMockDataSet()) except:
* FailingConnectionsAdapter is omitted because the BT standard doesn't include
any portable error codes.
* FailingGATTOperationsAdapter returns an ATT Error Response corresponding to
its UUID, instead of the Chromium-specific error code used in the current
Chromium tests.
@scheib @g-ortuno, can you double-check that I've matched the Chromium test APIs? This PR doesn't include the new interfaces I'm adding in https://codereview.chromium.org/1325953002/.
@yrliou @shuangMoz, we'd like your implementation to be able to share as many of our tests as possible. Please let us know what of this we need to change for it to work for you.
Rendered spec at …
> Start a specification for test-only APIs used in the Web Bluetooth tests.

- tests/index.bs
- tests/index.html
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/chooser-rescan-test/tests/index.html.
These are added to Chromium in https://codereview.chromium.org/1353053002.
> Add interfaces for testing that the chooser can restart discovery.

- tests/index.bs
- tests/index.html
This uses a callback rather than a promise because of an objection in
https://codereview.chromium.org/1351393002.
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/async-get-events/tests/index.html#test-runner.
> Make getBluetoothManualChooserEvents asynchronous.

- index.bs
- index.html
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/new-scan-filters/index.html#device-discovery.
I think I got all the places that assumed filters only had services, but please let me know if I missed any.
> Allow filtering by device name and name prefix in requestDevice().

- index.bs
- index.html
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/remove-script-execution-environment/index.html
@bzbarsky It looks like other specs leave platform objects' global environments implied rather than explicitly wired, so I'm following that convention here. I wound up using internal slots on the `Bluetooth` instance in nearly all cases, so I only needed to use that implied environment in one place: in https://rawgit.com/jyasskin/web-bluetooth-1/remove-script-execution-environment/index.html#service-change-events to find an event loop.
> Remove all mentions of "script execution environment", which no longer exists in HTML.

- index.bs
- index.html
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/read-value-ordering/index.html
@g-ortuno I'm being clever here with the adjacent tasks. Could you double-check that it looks reasonable to implement? `BluetoothDispatcher::OnReadValueSuccess` currently just resolves the promise, and doesn't fire any events. To avoid letting another value update come in before the event dispatches, we'd either need to run a microtask checkpoint (which I could just put in the spec...), queue a pair of tasks from `OnReadValueSuccess`, or send two adjacent IPCs to get the two tasks queued.
> Make readValue's .then() and event handlers execute in the same order they're mentioned in the spec.

- index.bs
- index.html
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/data-view/index.html.
> Fix #172: Return DataViews instead of ArrayBuffers.

- index.bs
- index.html
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/disconnect-event/index.html
I'm using `gattserverdisconnected` to distinguish this from non-gatt connections and from clients that disconnect once we implement peripheral mode.
This doesn't fully address #114.
> Add a gattserverdisconnected event to report when a page needs to reconnect.

- index.bs
- index.html
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/renames/index.html.
* BluetoothGATTRemoteServer -> BluetoothRemoteGATTServer
* BluetoothGATTService -> BluetoothRemoteGATTService
* BluetoothGATTCharacteristic -> BluetoothRemoteGATTCharacteristic
* BluetoothGATTDescriptor -> BluetoothRemoteGATTDescriptor
* BluetoothDevice.gattServer -> BluetoothDevice.gatt
What do people think of these changes?
> Add "Remote" to class names, and rename device.gattServer to device.gatt

- index.bs
Just a quick nit I discovered while experimenting with the APIs. This is awesome, thanks for your work on it!
> Remove extra closing paren from example code

- index.bs
- index.html
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/remove-device-info/index.html#bluetoothdevice.
These fields are in the API because it started life as [chrome.bluetooth.Device](https://developer.chrome.com/apps/bluetooth#type-Device), but they don't exist in either the [Core Bluetooth](https://developer.apple.com/library/ios/documentation/CoreBluetooth/Reference/CBPeripheral_Class/index.html) or (except for device class) the [Android](http://developer.android.com/reference/android/bluetooth/BluetoothDevice.html#lfields) APIs. Developers can still navigate the GATT tree to look them up; they just won't be available at the top level anymore.
I asked for opinions on doing this at
https://lists.w3.org/Archives/Public/public-web-bluetooth/2016Apr/0017.html
and the limited response was …
> Remove the device info and device class fields from BluetoothDevice.

- index.bs
- index.html
Instead of manually throwing an exception from requestDevice().
@mikewest, is [`[SecureContext]`](https://heycam.github.io/webidl/#SecureContext) ready to use here? Do you recommend putting it on just the entry function, or on all the interfaces? (It's also not implemented in Chrome yet, but I assume that's just a matter of time.)
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/secure-context-attribute/index.html#device-discovery
> Use the [SecureContext] IDL attribute to enforce secure contexts.

- index.bs
- index.html
Preview at https://rawgit.com/zakorgy/web-bluetooth/characteristic-writevalue/index.html#dom-bluetoothremotegattcharacteristic-writevalue.
This fixes #247.
> Check the Write property when calling WriteValue on characteristic

- index.bs
- index.html
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/eddystone-upgrade/index.html.
Much of the content in this patch is about letting a UA not constrain the set of services a site can access on a device that asked to open it. The threads at https://lists.w3.org/Archives/Public/public-web-bluetooth/2016Apr/0000.html and https://plus.sandbox.google.com/+FrancoisBeaufort/posts/jGBu1kxHbpZ didn't come to any firm conclusions on this point, but I think it makes sense to assume that a site advertised by a device is cooperating with that device, and so the normal purposes of showing the services list don't apply.
Fixes #163.
> Specify the Eddystone upgrade.

- index.bs
- index.html
- scanning.bs
- scanning.html
This doesn't cover scanning from a service worker yet.
Fixes #191.
Previews at https://rawgit.com/jyasskin/web-bluetooth-1/scanning/scanning.html and https://rawgit.com/jyasskin/web-bluetooth-1/scanning/index.html#bluetoothdevice
> Specify a Bluetooth Scanning API.

- index.bs
The CoreBluetooth API doesn't allow the UA to check the discoverable flags, so
we can't require it in the spec.
Fixes #141.
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/jyasskin/web-bluetooth-1/raw/discover-non-discoverable/index.bs#scan-for-devices
> Allow requestDevice() to include non-discoverable devices.

- index.bs
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/jyasskin/web-bluetooth-1/raw/block-blacklisted-gatt-children/index.bs#getgattchildren
Fixes #216.
> Don't return blacklisted attributes from GetGATTChildren().

- index.bs
I believe `sessionStorage.lastDevice` is unique, therefore it makes more sense to check for `length == 1`. If not, it should be at least `length >= 1` not `length > 1`.
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/WebBluetoothCG/web-bluetooth/raw/beaufortfrancois-patch-1/index.bs#example-permission-api-query
R=@jyasskin
> Fix nit in example code

- index.bs
These come from before I realized that "attribute" was the generic term for a service, characteristic, or descriptor.
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/jyasskin/web-bluetooth-1/raw/rename-entity-to-attribute/index.bs#service-change-events
> Use "attribute" instead of "entity" when appropriate.

- index.bs
Matches tc39/ecma262#591.
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/jyasskin/web-bluetooth-1/raw/remove-%40/index.bs.
> Use . instead of @ to refer to internal slots.

- index.bs
Marking them instead of saying their initial value is `undefined`, makes
it easier to see if I accidentally introduce an uninitialized path.
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/jyasskin/web-bluetooth-1/raw/mark-always-initialized-fields/index.bs#dom-bluetoothdevice-context-slot
> Mark internal slots that the spec always initializes.

- implementation-status.md
- index.bs
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/jyasskin/web-bluetooth-1/raw/match-requestDevice-filters-to-scanning/index.bs#device-discovery
> Make requestDevice()'s filters match requestLEScan()'s filters.

- index.bs
Following up on @g-ortuno's comment at https://github.com/WebBluetoothCG/web-bluetooth/pull/272#discussion_r74788592.
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/jyasskin/web-bluetooth-1/raw/explain-service-changed-algo/index.bs#example-changed-service
> Clarify how the ServiceChanged algorithm categorizes changes.

- implementation-status.md
- index.bs
`requestDevice({acceptAllDevices: true})` matches Scanning's
`requestLEScan({acceptAllAdvertisements: true})`.
Fixes #234.
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/open-filter/index.bs#device-discovery
@domenic, I'm not happy with how I expressed that exactly one of two fields in a dictionary must be present, especially since one of the fields is actually a boolean that's always present but I actually mean "true" for it. Do you have any suggestions? Also, "flag" arguments to algorithms: should I be using a boolean instead?
> Add a way to include all devices in the chooser.

- index.bs
Fixes #220.
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/clear-notifications-on-disconnection/index.bs#clean-up-the-disconnected-device.
> Clear the active notification context set on disconnection.

- index.bs
- scanning.bs
Definitions tend to be a bunch of text that flows imperceptibly into the
next definition. These boxes make it easier to know where to take a
breath.
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/boxed-algorithms/index.bs
@tabatkins, what do you think?
> Put nice boxes around each algorithm.

- index.bs
Since  `SecurityError: requestDevice() called with a filter containing a blacklisted UUID. https://goo.gl/4NeimX` links to "Attack on devices" section, it would be nice to have a link the GATT Blacklist section.
Live preview at https://api.csswg.org/bikeshed/?url=https://github.com/WebBluetoothCG/web-bluetooth/raw/beaufortfrancois-patch-2/index.bs#attacks-on-devices
> Add GATT blacklist link in "Attacks on devices"

- index.bs
Also add a note that connect() could wait forever if an appropriate
advertisement isn't received.
Fixes #152.
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/hanging-connect/index.bs#dom-bluetoothremotegattserver-connect.
> Make disconnect() abort connect().

- implementation-status.md
- index.bs
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/expose-availability/index.bs#availability.
Thanks to @domenic for simplifying the overall design.
@npdoty can you see if you agree with the [privacy section](https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/expose-availability/index.bs#availability-fingerprint) or if there's something different I should say?
> Expose whether Bluetooth is available.

- index.bs
It was hard to define the value of this field when a device's
advertisements may list varying sets of services and when the primary
services in the GATT server may be discovered gradually. Developers can
replace their uses of this field with uses of getPrimaryServices().
Fixes #290 
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/remove-uuids/index.bs. Please double-check that there's nothing else I can remove now that this field is gone.
> Remove the BluetoothDevice.uuids field.

- index.bs
- scanning.bs
Instead of overloading an empty allowedServices list to mean that GATT
is forbidden.
Fixes #283 
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/dont-overload-allowed-services/index.bs#dom-allowedbluetoothdevice-mayusegatt and https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/dont-overload-allowed-services/scanning.bs#advertising-events.
@g-ortuno @beaufortfrancois
> Define a mayUseGATT field in the extra permission data.

- implementation-status.md
- index.bs
https://heycam.github.io/webidl/#idl-exceptions says that SyntaxError is
"for use only by the ECMAScript parser". We use TypeError for bad enums,
so it makes sense for malformatted UUID strings too.
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/syntax-to-type-error/index.bs
> Throw a TypeError instead of a SyntaxError for bad UUIDs.

- index.bs
- scanning.bs
Previews at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/masked-data-prefixes/index.bs and https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/masked-data-prefixes/scanning.bs.
Fixes #294. @irgu
> Accept filters on manufacturer and service data.

- index.bs
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/specify-early-request-failures/index.bs#request-bluetooth-devices
Fixes #296 
@dati91
> Allow the UA to skip the chooser if no devices could appear in it.

- index.bs
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/in-progress-error/index.bs#dom-bluetoothremotegattserver-connect.
* GattServer.connect()
* Characteristic.readValue()
* Characteristic.writeValue()
* Characteristic.startNotifications()
* Descriptor.readValue()
* Descriptor.writeValue()
This is uncomfortable because while serializing within a single realm
will reduce the frequency of these NetworkErrors, separate realms and
possibly other applications entirely can also cause these errors, and
the only way to recover is to retry and hope it doesn't happen again.
We're discussing the constraints imposed by the OS and the long-term
plan in #188. Any change should reduce the number of exceptions and so
be backward-compatible.
> Allow UAs to reject concurrent use of 6 functions.

- index.bs
These are all unimplemented, and haven't been thought through as well as
the rest of the spec.
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/at-risk/index.bs#permission-api-integration.
> Mark sections that are more likely to change.

- index.bs
I think there is a typo in `GetPrimaryServices`, because `this{.device}` is used everywhere else but here.
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/dati91/web-bluetooth/raw/gattchildren_typo/index.bs
> Fix typo in GetPrimaryServices

- index.bs
The long list of examples has confused readers who arrived when searching for 
one pattern in particular. They saw the example and did not understand that
it was in a list where most examples were invalid. This change clearly marks
each example as valid or invalid.
https://api.csswg.org/bikeshed/?url=https://github.com/WebBluetoothCG/web-bluetooth/raw/invalid-request-device-examples/index.bs#example-disallowed-filters
> Clearly mark invalid requestDevice example arguments.

- index.bs
This is the same problem as in https://github.com/WICG/webusb/pull/67
Here, too, sprinkle some [SameObject] around.
> Let Bluetooth inherit from EventTarget

- index.bs
https://heycam.github.io/webidl/#SameObject says we can only use it on
interfaces, not Promises, FrozenArrays, primitive types, or nullable interfaces.
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/same-object/index.bs
> Add [SameObject] to all unchanging interface attributes.

- index.bs
Instead of a custom [[data]] slot that also holds an EcmaScript Map.
Fixes #340 
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/use-backing-map/index.bs#dom-bluetoothadvertisingevent-bluetoothadvertisingevent
> Use the [[BackingMap]] provided by the ES maplike binding.

- index.bs
Add a link for the bluetooth permission request part, make it referenceable by code writers .
Preview at: https://api.csswg.org/bikeshed/?url=https://github.com/zakorgy/web-bluetooth/raw/permission-request-link/index.bs#request-the-bluetooth-permission
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/353)
> Add link for the request bluetooth permission

- index.bs
Fixes  #341.
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/zakorgy/web-bluetooth/raw/reorder-startnot-steps/index.bs#dom-bluetoothremotegattcharacteristic-startnotifications
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/355)
> Reorder startNotifications steps

- index.bs
This PR fixes #347, also removes the numbering from the Note element in the query algorithm.
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/zakorgy/web-bluetooth/raw/permission-request/index.bs#query-the-bluetooth-permission.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/349)
> Fixes for the Permission API integration part.

- index.bs
Fixes #346.
My impression is that we can't control Mac's bonding behavior, so we can't provide a function to let the website request bonding. Having a bond seems like it's always more secure than not having one, and the main downside of trying to bond would be that we might show a pin-entry dialog if that's the pairing method the devices negotiate. Showing that dialog on connection seems better than showing it when the first secure characteristic is accessed.
> Allow the UA to bond while connecting.

- tests.bs
> Fix the link for TestRunner.getBluetoothManualChooserEvents(callback).

- index.bs
A common violation of the specification is characteristics with
notification/indication capabilities not having an associated
Client Characteristic Configuration descriptor (CCCD).
In order to allow compatability with these types of devices,
implementaions should still attempt to register notifications on
characteristics without a CCD.
> Handle notifications for characteristics missing a CCCD

- scanning.bs
Bikeshed compilation fails when encountering the former with,
"Unknown inline tag: non-`null`"
Replacing this with "not `null`" does not change the meaning.
> Replace "non-`null`" with "not `null`"

- index.bs
- scanning.bs
- tests.bs
This patch exports definitions related to Permissions API integration, adds a few references to unexported definitions where they are appropriate and removes a few definitions that are unused.
> Fix warnings for unexported definitions

- .pr-preview.json
See https://github.com/tobie/pr-preview#configuration-file for documentation.
This only supports the main Web Bluetooth specification. https://github.com/tobie/pr-preview/issues/18 tracks being able to preview the scanning spec as well.
> Add a PR-Preview configuration file

- index.bs
It is tricky sometimes to know why the Web Bluetooth API is not "working" as `navigator.bluetooth` is available in HTTP, but `navigator.bluetooth.requestDevice` only in HTTPS. I propose adding `[SecureContext]` to `navigator.bluetooth` as well.
WDYT @jyasskin 
CC @g-ortuno
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/401.html" title="Last updated on Jul 6, 2018, 4:11 PM GMT (e7a3afb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/401/68c5a71...e7a3afb.html" title="Last updated on Jul 6, 2018, 4:11 PM GMT (e7a3afb)">Diff</a>
> Add [SecureContext] to navigator.bluetooth

- index.bs
This is a followup to #401 and adds the [SecureContext] attribute to all remaining interfaces.
***
<a href="https://pr-preview.s3.amazonaws.com/reillyeon/web-bluetooth/pull/402.html" title="Last updated on Jul 7, 2018, 12:32 AM GMT (f678ab3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/402/f387d3a...reillyeon:f678ab3.html" title="Last updated on Jul 7, 2018, 12:32 AM GMT (f678ab3)">Diff</a>
> Add [SecureContext] attribute to all interfaces

- index.bs
See https://github.com/heycam/webidl/pull/423 and https://github.com/heycam/webidl/pull/433 for more information.
***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/web-bluetooth/pull/415.html" title="Last updated on Nov 19, 2018, 12:31 AM GMT (b0e1340)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/415/ed01e98...saschanaz:b0e1340.html" title="Last updated on Nov 19, 2018, 12:31 AM GMT (b0e1340)">Diff</a>
> Add [Exposed] and migrate to new mixin syntax

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/dougt/web-bluetooth/pull/418.html" title="Last updated on Dec 10, 2018, 6:50 PM GMT (58a0752)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/418/742618d...dougt:58a0752.html" title="Last updated on Dec 10, 2018, 6:50 PM GMT (58a0752)">Diff</a>
> Use actual type for Maps in BluetoothAdvertisingEventInit

- scanning.bs
In Example 1, | keepRepeatedDevices| is inside |options|.  However, BluetoothLEScanOptions is defined as follows:
dictionary BluetoothLEScanOptions {
sequence<BluetoothLEScanFilterInit> filters;
boolean keepRepeatedDevices = false;
boolean acceptAllAdvertisements = false;
};
So, we should strike |options| from the example.
> Update example to not include |options| attribute

- index.bs
This event type was defined but the EventHandler attribute was missing
from the BluetoothDevice interface. This change adds it to the
BluetoothDeviceEventHandlers mixin so that it is also present on the
Bluetooth interface for bubbled events.
Fixes #426.
***
<a href="https://pr-preview.s3.amazonaws.com/reillyeon/web-bluetooth/pull/427.html" title="Last updated on Feb 12, 2019, 1:33 AM UTC (2c22fa0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/427/0c85d25...reillyeon:2c22fa0.html" title="Last updated on Feb 12, 2019, 1:33 AM UTC (2c22fa0)">Diff</a>
> Add 'onadvertisementreceived' attribute to BluetoothDeviceEventHandlers

- implementation-status.md
Clarify that Chrome only supports the Windows 10 version 1706 (Creators Update) and later.
> Add Windows version requirements implementation-status.md

- index.bs
Following https://github.com/WebBluetoothCG/web-bluetooth/issues/238, this PR adds two new methods to `BluetoothRemoteGATTCharacteristic` to write values with and without response.
Steps to get live preview:
1. Go to https://api.csswg.org/bikeshed/
2. In "Load from URL", enter https://raw.githubusercontent.com/WebBluetoothCG/web-bluetooth/write-response/index.bs
3. Click "Process" button
> Add Characteristic Write w/o Response methods

- index.bs
This change updates the Exposing Bluetooth availability and the
getAvailability() algorithm definition to explicitly mention that the
Bluetooth adapter powered state is not considered when determining the
availability.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/443.html" title="Last updated on Jun 14, 2019, 10:09 PM UTC (2d054ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/443/8c79d31...odejesush:2d054ae.html" title="Last updated on Jun 14, 2019, 10:09 PM UTC (2d054ae)">Diff</a>
> Clarify getAvailability for BT radio powered state

- index.bs
- scanning.bs
Algorithms for working with Promises have moved from [promises-guide] to [WebIDL].
This change also creates an anchor for the "initializing the Document object" algorithm in the HTML specification. This may not be the right way of extending this algorithm with additional steps.
***
<a href="https://pr-preview.s3.amazonaws.com/reillyeon/web-bluetooth/pull/456.html" title="Last updated on Sep 30, 2019, 7:27 PM UTC (e1f3994)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/456/5d16c73...reillyeon:e1f3994.html" title="Last updated on Sep 30, 2019, 7:27 PM UTC (e1f3994)">Diff</a>
> Migrate to references exported from the WebIDL spec

- index.bs
Just fix the following format issue:
***
<a href="https://pr-preview.s3.amazonaws.com/yorkie/web-bluetooth/pull/457.html" title="Last updated on Oct 23, 2019, 12:28 PM UTC (142c9c2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/457/720be21...yorkie:142c9c2.html" title="Last updated on Oct 23, 2019, 12:28 PM UTC (142c9c2)">Diff</a>
> index: fix the unneeded spaces at example lines

- index.bs
Add details on the interaction between the Bluetooth availability and Bluetooth permission. This should help to resolve some of the confusion brought up in #459.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/461.html" title="Last updated on Nov 4, 2019, 10:28 PM UTC (9153fa2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/461/5f57c59...odejesush:9153fa2.html" title="Last updated on Nov 4, 2019, 10:28 PM UTC (9153fa2)">Diff</a>
> Clarify availability permission relationship

- index.bs
- scanning.bs
This change updates the "request Bluetooth devices" algorithm to refer
to the User Activation v2 model. The algorithm now has to be triggered
while its relevant global object has a transient activation before being
allowed to continue.
This fixes #463.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/470.html" title="Last updated on Feb 11, 2020, 7:08 PM UTC (2336d55)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/470/9991588...odejesush:2336d55.html" title="Last updated on Feb 11, 2020, 7:08 PM UTC (2336d55)">Diff</a>
> Update language for User Activation v2

- index.bs
This change updates the spec source file to use more Markdown syntax in
order to improve the readability. This commit updates the spec from
Section 1 to Section 3.
The following changes were performed:
* Heading tags were replaced with their Markdown equivalent, #.
* \<p\> tags were removed.
* \<ol\>, \<ul\>, and \<li\> tags were replaced with their Markdown equivalent, * and 1.
* \<table\> CSS was updated to match the tables in the WebUSB spec so that
they didn't overflow past the containers that were holding them.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/469.html" title="Last updated on Feb 11, 2020, 9:58 PM UTC (55cdebe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/469/4ca7ccb...odejesush:55cdebe.html" …
> Use Markdown for Sections 1-3

- index.bs
This change updates the spec source file to use more Markdown syntax in
order to improve readability. This commit updates the Section 4 of the
spec.
The following changes were performed:
* Heading tags were replaced with their Markdown equivalent, #.
* \<p\> tags were removed.
* \<ol\>, \<ul\>, \<li\> tags were reaplced with their Markdown equivalent, *
and 1.
* \<table\> tags had the "data" class removed to fix their rendering so
that they don't overflow past their containers.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/471.html" title="Last updated on Feb 11, 2020, 10:29 PM UTC (4fa9fb6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/471/0534be7...odejesush:4fa9fb6.html" title="Last updated on Feb 11, 2020, …
> Use Markdown for Section 4

- index.bs
This change updates the spec source file to use more Markdown syntax in
order to improve readability. This commit updates Section 5 of the spec.
The following changes were performed:
* `<div class="issue">` were replaced with `Issue:`.
* Heading tags were replaced with their Markdown equivalent, `#`.
* `<p>` tags were removed.
* `<ol>`, `<ul>`, `<li>` tags were replaced with their Markdown equivalent,
`*` and `1`.
* `<table>` tags had the `data` class removed to fix their rendering such
that they don't overflow past their containers.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/472.html" title="Last updated on Feb 13, 2020, 12:34 AM UTC (5c7c85f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/472/0534be7...odejesush …
> Use Markdown for Section 5

- index.bs
This change updates the spec source file to use more Markdown syntax in
order to improve readability. This commit updates Sections 6 to 9 of the
spec. Most of Section 9 still maintains its list in HTML, since it uses
specific numbering and lists with letters.
The following changes were performed:
* Heading tags were replaced with their Markdown equivalent, `#`.
* `<p>` tags were removed.
* `<ol>`, `<ul>`, and `<li>` tags were replaced with their Markdown
equivalent, `*` and `1.`.
* `<table>` tags had the `data` class removed to fix their rendering
such that they don't overflow past their containers.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/473.html" title="Last updated on Feb 13, 2020, 6:55 PM UTC (fe20294)">Preview</a> | <a …
> Use Markdown for Sections 6-9

- index.bs
The algorithms related to GATT descriptos have been implemented in
Chromium, therefore they are stable now. The following have been marked
as stable:
* BluetoothRemoteGATTCharacteristic getDescriptor algorithm
* BluetoothRemoteGATTCharacteristic getDescriptors algorithm
* BluetoothRemoteGATTDescriptor interface
* BluetoothRemoteGATTDescriptor create algorithm
* BluetoothRemoteGATTDescriptor readValue algorithm
* BluetoothRemoteGATTDescriptor writeValue algorithm
See
https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/bluetooth/
for Chromium implementation.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/475.html" title="Last updated on Feb 13, 2020, 7:31 PM UTC (fca6873)">Preview</a> | <a …
> Mark GATT descriptors as stable

- index.bs
This change adds a getDevices() method to the Bluetooth interface to
make the API more consistent with other device APIs, such as [WebUSB](https://wicg.github.io/webusb).
Additionally, this change renames BluetoothPermissionData to
BluetoothPermissionStorage for consistency with other device APIs and
clarifies how Bluetooth device permissions are added to
BluetoothPermissionStorage.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/476.html" title="Last updated on Feb 19, 2020, 10:53 PM UTC (0998f43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/476/a5451b1...odejesush:0998f43.html" title="Last updated on Feb 19, 2020, 10:53 PM UTC (0998f43)">Diff</a>
> Add Bluetooth.getDevices and permission storage

- deploy.sh
This change makes errors in parsing the spec source files more visible
by adding more verbose logging with color.
> Add logging and color to deploy script

- deploy.sh
- index.bs
This change updates the algorithms for `watchAdvertisements()` and `unwatchAdvertisements()` to use the same parallel queue in order to prevent a race condition from happening when sending instructions to the OS to start/stop Bluetooth discovery for the device.
***
:boom: ###
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 12, 2020, 10:01 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fpr-preview.s3.a …
> Fix race condition in {,un}watchAdvertisements()

- index.bs
Refactor [`watchAdvertisements()`](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothdevice-watchadvertisements) to take an [`AbortSignal`](https://dom.spec.whatwg.org/#abortsignal) parameter from an
[`AbortController`](https://dom.spec.whatwg.org/#abortcontroller)` to cancel the operation when the signal's aborted flag
is set. As a result, unwatchAdvertisements() is no longer needed as it's
operation is replaced by the AbortController [abort steps](https://dom.spec.whatwg.org/#abortsignal-add).
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/480.html" title="Last updated on Mar 20, 2020, 5:03 PM UTC (6c16e07)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/480/cbd2a81...odejesush:6c16e07.html" title="Last …
> Use AbortController for watchAdvertisements()

- index.bs
- scanning.bs
This change adds a handler for loss of full activity that stops any on-going Bluetooth scans. This is to mitigate an identity risk that is present if two sites are watching for device advertisements and receive the same advertisement at the same time.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/481.html" title="Last updated on Mar 20, 2020, 5:36 PM UTC (7ce50e4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/481/e8635ae...odejesush:7ce50e4.html" title="Last updated on Mar 20, 2020, 5:36 PM UTC (7ce50e4)">Diff</a>
> Abort Bluetooth discovery when focus is lost

- scanning.bs
For coherence with other steps.
> Missing "this."

- scanning.bs
I guess `serviceUUID` has been replaced by `services` (array of `UUID`) in `BluetoothLEScanFilter`. Please check this is ok before merging.
> serviceUUID does not exist in definition of BluetoothLEScanFilter

- index.bs
This is to make it consistent with how manufacturerData is defined
***
<a href="https://pr-preview.s3.amazonaws.com/SinZ163/web-bluetooth/pull/491.html" title="Last updated on May 3, 2020, 4:21 AM UTC (94ec189)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/491/b8f5a20...SinZ163:94ec189.html" title="Last updated on May 3, 2020, 4:21 AM UTC (94ec189)">Diff</a>
> Correct a minor error in BluetoothAdvertisingEvent's constructor algorithm

- index.bs
I added the missing 's' from the end of `navigator.permissions`, and a link to the `query` doc.
***
<a href="https://pr-preview.s3.amazonaws.com/Totati/web-bluetooth/pull/496.html" title="Last updated on May 9, 2020, 6:50 PM UTC (375fe6e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/496/16d2ef9...Totati:375fe6e.html" title="Last updated on May 9, 2020, 6:50 PM UTC (375fe6e)">Diff</a>
> Fix example (#495)

- index.bs
This deprecates `BluetoothRemoteGATTCharacteristic.writeValue()` in favor of `writeValueWithResponse()` and `writeValueWithoutResponse()`. 
Based on recent discussion in issue #238, `writeValue()` is marked as deprecated and the property checking requirement is removed.
***
<a href="https://pr-preview.s3.amazonaws.com/pybricks/web-bluetooth/pull/497.html" title="Last updated on May 11, 2020, 10:28 PM UTC (a95d780)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/497/58705c1...pybricks:a95d780.html" title="Last updated on May 11, 2020, 10:28 PM UTC (a95d780)">Diff</a>
> Deprecate BluetoothRemoteGATTCharacteristic.writeValue()

- implementation-status.md
Support for remote GATT write characteristic with and without response has been added in Chromium 85.
> update implementation status for write with/without response

- implementation-status.md
This change updates the implementation status for Persistent
Permissions, `getDevices()`, and `watchAdvertisements()`.
> Update Implementation Status for Persistent Permissions Feature

- index.bs
This change adds steps to stop a scan operations started by
watchAdvertisements() when the page visibility state is not "visible".
This change also removes the "unstable" class from watchAdvertisements
and abort watchAdvertisements.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/504.html" title="Last updated on Jul 1, 2020, 10:26 PM UTC (2d8e278)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/504/0a0b9e1...odejesush:2d8e278.html" title="Last updated on Jul 1, 2020, 10:26 PM UTC (2d8e278)">Diff</a>
> Handle Visibility Change for watchAdvertisements

- index.bs
- scanning.bs
This change updates the specification so that Service UUID and Manufacturer data is filtered out from `BluetoothAdvertisingEvent`s depending on the `RequestDeviceOptions` used when the device permission was granted to the site.
This change also removes references to the Permissions API `request()` algorithm because it is no longer included in that spec and was causing Bikeshed errors.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/505.html" title="Last updated on Jul 30, 2020, 8:25 PM UTC (19e0431)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/505/373de24...odejesush:19e0431.html" title="Last updated on Jul 30, 2020, 8:25 PM UTC (19e0431)">Diff</a>
> Filter Services and Manufacturer Data from AD

- index.bs
Fixes #524
***
<a href="https://pr-preview.s3.amazonaws.com/motla/web-bluetooth/pull/525.html" title="Last updated on Sep 23, 2020, 9:35 PM UTC (6c991a0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/525/0af495e...motla:6c991a0.html" title="Last updated on Sep 23, 2020, 9:35 PM UTC (6c991a0)">Diff</a>
> Consistency issues fix

- scanning.bs
Following discussions from PR https://github.com/WebBluetoothCG/web-bluetooth/pull/520 & PR https://github.com/WebBluetoothCG/web-bluetooth/pull/523
[Bikeshed preview](https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/motla/web-bluetooth/patch-5/scanning.bs)
> Rewriting .map() to Array.prototype.map.call() / making BluetoothLEScanFilter.services non-nullable

- index.bs
- scanning.bs
- tests.bs
w3c/permissions#229 moved all the canonical `PermissionName` definitions into the permissions spec.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/web-bluetooth-1/pull/540.html" title="Last updated on Feb 22, 2021, 11:44 PM UTC (555b225)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/540/f8ce14d...jyasskin:555b225.html" title="Last updated on Feb 22, 2021, 11:44 PM UTC (555b225)">Diff</a>
> Fix links to PermissionName/"bluetooth" after w3c/permissions#229.

- .github/workflows/pr-push.yml
This change configures GitHub Actions to build the specification and associated documents using Bikeshed through [Spec Prod](https://github.com/w3c/spec-prod).
> Configure GitHub Actions

- index.bs
- scanning.bs
This PR fixes the Bikeshed linking errors below:
```
LINK ERROR: No 'enum-value' refs found for '"bluetooth"' with spec 'web-bluetooth'.
{{"bluetooth"}}
✔ Successfully generated, with 1 linking errors
```
```
LINK ERROR: No 'dfn' refs found for 'context object'.
<a data-link-type="dfn" data-lt="context object">context object</a>
✘  Did not generate, due to fatal errors
```
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/546.html" title="Last updated on Apr 27, 2021, 1:48 PM UTC (0008a92)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/546/d5dbc97...0008a92.html" title="Last updated on Apr 27, 2021, 1:48 PM UTC (0008a92)">Diff</a>
> Fix Bikeshed linking error

- index.bs
- scanning.bs
The more I'm playing with manufacturer data filters, the more I think we should go with a `sequence` instead of a `map` in [BluetoothLEScanFilterInit](https://webbluetoothcg.github.io/web-bluetooth/#dictdef-bluetoothlescanfilterinit) for both `manufacturerData` and `serviceData`.
Because users can have different strings to express the same uint16 ('0' and '00' for instance), we'll have to check for the unicity of the key which is what we're doing already with a sequence.
Moreover, having a required `companyIdentifier` dictionary key seems more readable than a simple object key.
I've added some code samples below to give you an idea of what I'm experiencing.
```js
// It's not easy to understand what we're filtering on at first glance and the
// empty object isn't nice to read as well.
let …
```
> Use sequence instead of map for data filters

- index.bs
This PR removes "unstable" class for manufacturer data filter.
@reillyeon PTAL
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/549.html" title="Last updated on May 17, 2021, 8:33 AM UTC (0281e8e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/549/8447b7c...0281e8e.html" title="Last updated on May 17, 2021, 8:33 AM UTC (0281e8e)">Diff</a>
> Remove unstable for manufacturer data filter

- implementation-status.md
Secure characteristics may only be accessed on paired devices.
Note those platforms which currently pair on-demand when accessing
a secure characteristic.
> Documented Chrome's on-demand pairing.

- index.bs
- scanning.bs
- tests.bs
As part of https://github.com/w3c/permissions/issues/263, we're making sure powerful features are properly defined in their specs. (Web Bluetooth does a great job, btw).
[PermissionName enum may go away](https://github.com/w3c/permissions/issues/314) from the permissions spec (maybe just moved into a different registry), so this PR defines "bluetooth" as a powerful feature here to be safe.
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/web-bluetooth/pull/565.html" title="Last updated on Nov 12, 2021, 11:20 PM UTC (03d8f1b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/565/97981b7...miketaylr:03d8f1b.html" title="Last updated on Nov 12, 2021, 11:20 PM UTC (03d8f1b)">Diff</a>
> Define "bluetooth" as a powerful feature without referencing PermissionEnum

- index.bs
The "allowed in non-secure contexts flag" export was removed from Permissions.
https://github.com/w3c/permissions/pull/327
> Editorial: unlink "allowed in non-secure contexts flag"

- index.bs
> It looks like you'll need to create an update to how this specification references the Permissions API before this PR can be merged.
I've fixed this by following https://github.com/whatwg/storage/pull/136 example.
_Originally posted by @beaufortfrancois in https://github.com/WebBluetoothCG/web-bluetooth/issues/574#issuecomment-1060653327_
PTAL @reillyeon
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/577.html" title="Last updated on Mar 8, 2022, 12:00 PM UTC (046ca9b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/577/b5f7617...046ca9b.html" title="Last updated on Mar 8, 2022, 12:00 PM UTC (046ca9b)">Diff</a>
> Use string literal for permission name

- index.bs
- scanning.bs
- tests.bs
- use-cases.bs
Similarly to [HIDDevice.forget()](https://chromestatus.com/feature/5723581527883776) and [USBDevice forget()](https://chromestatus.com/feature/5640127995969536), this PR adds BluetoothDevice.forget() so that web developers can revoke permission access to a paired BluetoothDevice.
```js
// Request a Bluetooth device.
const device = await navigator.bluetooth.requestDevice({ acceptAllDevices: true });
// Then later... revoke permission to the Bluetooth device.
await device.forget();
```
@reillyeon Please have a look
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/574.html" title="Last updated on Apr 11, 2022, 8:34 AM UTC (bea3a26)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/574/cecb7f1...bea3a26.html" title="Last …
> Add BluetoothDevice.forget()

- index.bs
- scanning.bs
This PR specifies the integration of the Web Bluetooth API with Permissions Policy, so that developers have more control over Bluetooth availability, especially in cross-origin iframe scenarios. 
[index.bs preview](https://api.csswg.org/bikeshed/?url=https://github.com/gabrielsanbrito/web-bluetooth/raw/permissions-policy-integration/index.bs)
[scanning.bs preview](https://api.csswg.org/bikeshed/?url=https://github.com/gabrielsanbrito/web-bluetooth/raw/permissions-policy-integration/scanning.bs)
@reillyeon PTAL when convenient.
Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/gabrielsanbrito/web-bluetooth/pull/582.html" title="Last updated on Apr 13, 2022, 8:24 PM UTC (9b3dd28)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/582/f9ee525...gab …
> Permissions Policy integration

- index.bs
This PR fixes bikeshed issue below:
```
$ bikeshed --die-on=warning spec "index.bs" "index.bs.built.html" 
LINK ERROR: No 'enum-value' refs found for '"denied"' with spec 'permissions-1'.
{{"denied"}}
✘  Did not generate, due to fatal errors
```
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/601.html" title="Last updated on Mar 24, 2023, 12:05 PM UTC (c9615cc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/601/696bb7a...c9615cc.html" title="Last updated on Mar 24, 2023, 12:05 PM UTC (c9615cc)">Diff</a>
> Fix bikeshed issue with 'denied'

- implementation-status.md
- index.bs
This PR is about a new `"exclusionFilters"` option in `navigator.bluetooth.requestDevice()` options so that developers can exclude from the browser picker some known devices that are known to not work as expected.
Note that the name comes from the WebHID spec: https://github.com/WICG/webhid/pull/93
FIX https://github.com/WebBluetoothCG/web-bluetooth/issues/599
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/600.html" title="Last updated on Mar 24, 2023, 1:45 PM UTC (2677632)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/600/4cb5684...2677632.html" title="Last updated on Mar 24, 2023, 1:45 PM UTC (2677632)">Diff</a>
> Add exclusionFilters to RequestDeviceOptions

- index.bs
- use-cases.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/608.html" title="Last updated on Jul 14, 2023, 10:48 PM UTC (15148eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/608/5c259bb...15148eb.html" title="Last updated on Jul 14, 2023, 10:48 PM UTC (15148eb)">Diff</a>
> Disambiguate reference to "children"

- index.bs
This is a spec patch to use the manufacturer data block list in https://github.com/WebBluetoothCG/registries/blob/master/manufacturer_data_blocklist.txt.
The spec patch follows how we did for [crrev.com/c/3781118](https://crrev.com/c/3781118).
***
<a href="https://pr-preview.s3.amazonaws.com/chengweih001/web-bluetooth/pull/611.html" title="Last updated on Aug 28, 2023, 10:04 PM UTC (f6f52eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/611/7096b82...chengweih001:f6f52eb.html" title="Last updated on Aug 28, 2023, 10:04 PM UTC (f6f52eb)">Diff</a>
> Add manufacturer data blocklist

- requestLEScan-for-granted-devices-explainer.md
Hi Web Bluetooth owner,
Could you please review this explainer that we would like to expand the existing requestLEScan to support listing for advertisements from granted devices as an alternative to the exiting [WatchAdvertisements](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothdevice-watchadvertisements) API.
> Explainer for requestLEScan for granted devices

- index.bs
Closes https://github.com/WebBluetoothCG/web-bluetooth/issues/616
***
<a href="https://pr-preview.s3.amazonaws.com/OrKoN/web-bluetooth/pull/622.html" title="Last updated on Apr 11, 2024, 5:07 AM UTC (2d8cfac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/622/7b56ee8...OrKoN:2d8cfac.html" title="Last updated on Apr 11, 2024, 5:07 AM UTC (2d8cfac)">Diff</a>
> Add WebDriver BiDi extension

- index.bs
This PR fixes #626 by correcting the WebDriver spec's  dfn url.
***
<a href="https://pr-preview.s3.amazonaws.com/alvinjiooo/web-bluetooth/pull/627.html" title="Last updated on May 15, 2024, 9:34 PM UTC (9e9917c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/627/35c034e...alvinjiooo:9e9917c.html" title="Last updated on May 15, 2024, 9:34 PM UTC (9e9917c)">Diff</a>
> Fix WebDriver dfn url error

- index.bs
- scanning.bs
Fixed #628.
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/629.html" title="Last updated on Jul 22, 2024, 9:56 PM UTC (c0ca0c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/629/0fa7040...c0ca0c9.html" title="Last updated on Jul 22, 2024, 9:56 PM UTC (c0ca0c9)">Diff</a>
> Update "browser context" to "navigable" in WebDriver integration

- index.bs
This PR is changing [`BluetoothManufacturerData.data` from being a `bstr`](https://github.com/WebBluetoothCG/web-bluetooth/pull/630#discussion_r1783657473) and defining it as a base64 encoded text representation as a `tstr`. Since BiDi is a protocol over JSON, this seems the correct way to represent bytes per [RFC 8610](https://datatracker.ietf.org/doc/html/rfc8610#appendix-E).
***
<a href="https://pr-preview.s3.amazonaws.com/alexnj/web-bluetooth/pull/633.html" title="Last updated on Oct 8, 2024, 5:48 PM UTC (ee06d56)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/633/5fca8d9...alexnj:ee06d56.html" title="Last updated on Oct 8, 2024, 5:48 PM UTC (ee06d56)">Diff</a>
> Change BlutoothManufacturerData.data to base64-encoded tstr

- .github/workflows/pr-push.yml
- index.bs
- scanning.bs
- use-cases.bs
Bikeshed requires Python 3.9, which is not available in Ubuntu 20.04.
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/638.html" title="Last updated on Jan 9, 2025, 12:16 AM UTC (13ca27f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/638/f3b3187...13ca27f.html" title="Last updated on Jan 9, 2025, 12:16 AM UTC (13ca27f)">Diff</a>
> Update GitHub Action to ubuntu-latest

- index.bs
The typedefs `BluetoothServiceUUID`, `BluetoothCharacteristicUUID`, and `BluetoothDescriptorUUID` are **normative** IDL constructs, but their formal definition was in an **informative** Note.
This update drops the wrapping Note to make the definitions normative as well.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 2, 2024, 3:04 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Ftidoust%2Fweb-blue …
> Make definitions of typedefs normative

- index.bs
This fixes the algorithms identified by #641 as resolving or rejecting a Promise while running in parallel without first queuing a task.
There are a lot of other issues with the algorithms in this spec and while I've cleaned up the text immediately around the affected algorithms much has been left as-is to avoid rewriting the world.
Fixed #641.
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/643.html" title="Last updated on Feb 8, 2025, 12:25 AM UTC (046b4ce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/643/f95942c...046b4ce.html" title="Last updated on Feb 8, 2025, 12:25 AM UTC (046b4ce)">Diff</a>
> Rewrite index.bs to always queue a task before resolving a Promise

- index.bs
This change fixes the steps for handling visibility change and loss of full activity to find the global object for the Document which experienced the event and from there identify the Bluetooth object for which we need to take action.
This introduces the concept of an "associated Bluetooth", similar to an "associated Document" and adds a "Bluetooth task source" which is now used whenever queuing a task.
Fixed #593.
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/595.html" title="Last updated on Feb 10, 2025, 10:48 PM UTC (6832b3c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/595/4816de7...6832b3c.html" title="Last updated on Feb 10, 2025, 10:48 PM UTC (6832b3c)">Diff</a>
> Fix visibility change and loss of full activity events

- index.bs
As an extenion to the Web Bluetooth API it needs access to the "Bluetooth task source" and "assocaited Bluetooth" definitions.
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/644.html" title="Last updated on Feb 13, 2025, 6:49 PM UTC (14a8404)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/644/030375d...14a8404.html" title="Last updated on Feb 13, 2025, 6:49 PM UTC (14a8404)">Diff</a>
> Export definitions required by the Scanning API

- scanning.bs
This fixes the algorithms identified by #642 as resolving or rejecting a Promise while running in parallel without first queuing a task.
Fixed #642.
> Rewrite scanning.bs to always queue a task before resolving a Promise

- index.bs
Update `bluetooth.simulateAdapter` command to support creating, updating, and removing adapter.
***
<a href="https://pr-preview.s3.amazonaws.com/chengweih001/web-bluetooth/pull/646.html" title="Last updated on Feb 21, 2025, 10:23 PM UTC (6d9537f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/646/d2d4d06...chengweih001:6d9537f.html" title="Last updated on Feb 21, 2025, 10:23 PM UTC (6d9537f)">Diff</a>
> Update bluetooth.simulateAdapter command

- index.bs
This patch specifies the behavior when the parameter of `type` of `bluetooth.simulateAdapter` is not supported.
***
<a href="https://pr-preview.s3.amazonaws.com/chengweih001/web-bluetooth/pull/647.html" title="Last updated on Feb 28, 2025, 6:36 PM UTC (eb22999)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/647/6309029...chengweih001:eb22999.html" title="Last updated on Feb 28, 2025, 6:36 PM UTC (eb22999)">Diff</a>
> Return error when type is not supported in bluetooth.simulateAdapter

- index.bs
- scanning.bs
This pull request moves `type` == `remove` from `bluetooth.simulateAdapter` to a new command `bluetooth.disableSimulation`. The goal is to make it clear that the effect of `bluetooth.simulateAdapter` would end up with a simulated adapter, while `bluetooth.disableSimulation` would remove the simulation entirely.
***
<a href="https://pr-preview.s3.amazonaws.com/chengweih001/web-bluetooth/pull/648.html" title="Last updated on Mar 11, 2025, 1:40 AM UTC (fcdb0ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/648/22c5b49...chengweih001:fcdb0ee.html" title="Last updated on Mar 11, 2025, 1:40 AM UTC (fcdb0ee)">Diff</a>
> New bluetooth.disableSimulation command for Web Bluetooth automation

- index.bs
Required for proper handling WeebDriver BiDi commands.
***
<a href="https://pr-preview.s3.amazonaws.com/sadym-chromium/web-bluetooth/pull/649.html" title="Last updated on Mar 26, 2025, 10:31 PM UTC (c53088a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/649/7066ce3...sadym-chromium:c53088a.html" title="Last updated on Mar 26, 2025, 10:31 PM UTC (c53088a)">Diff</a>
> build: extract aggregated `BluetoothCommand` cddl type

- index.bs
Add new WebDriver Bidi command and event for Web Bluetooth automation:
- bluetooth.gattConnectionAttempted: Event upon GATT connection attempt.
- bluetooth.simulateGattConnectionResponse: For simulating the response for a GATT connection attempt.
***
<a href="https://pr-preview.s3.amazonaws.com/chengweih001/web-bluetooth/pull/650.html" title="Last updated on Apr 16, 2025, 4:42 AM UTC (34b4996)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/650/c845e58...chengweih001:34b4996.html" title="Last updated on Apr 16, 2025, 4:42 AM UTC (34b4996)">Diff</a>
> bluetooth.gattConnectionAttempted and bluetooth.simulateGattConnectionResponse for Web Bluetooth automation

- index.bs
Add bluetooth.SimulateGattDisconnection WebDriver Bidi command for Web Bluetooth Automation.
***
<a href="https://pr-preview.s3.amazonaws.com/chengweih001/web-bluetooth/pull/651.html" title="Last updated on Apr 21, 2025, 11:11 PM UTC (2e5191f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/651/d9e74bf...chengweih001:2e5191f.html" title="Last updated on Apr 21, 2025, 11:11 PM UTC (2e5191f)">Diff</a>
> Add bluetooth.SimulateGattDisconnection

- index.bs
Add the following WebDriver Bidi commands and events for Web Bluetooth automation.
- bluetooth.SimulateService
- bluetooth.SimulateCharacteristic
- bluetooth.simulateCharacteristicResponse
- bluetooth.SimulateDescriptor
- bluetooth.simulateDescriptorResponse
- bluetooth.CharacteristicEventGenerated
- bluetooth.DescriptorEventGenerated
The detail algorithm for each of the those commands and events will be completed in future PRs.
***
<a href="https://pr-preview.s3.amazonaws.com/chengweih001/web-bluetooth/pull/654.html" title="Last updated on May 1, 2025, 10:18 PM UTC (b4d48c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/654/d940d56...chengweih001:b4d48c9.html" title="Last updated on May 1, 2025, 10:18 PM UTC (b4d48c9)">Diff</a>
> Add WebDriver Bidi commands

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/chengweih001/web-bluetooth/pull/652.html" title="Last updated on May 2, 2025, 10:50 PM UTC (66d1527)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/652/4cc1268...chengweih001:66d1527.html" title="Last updated on May 2, 2025, 10:50 PM UTC (66d1527)">Diff</a>
> Support bluetooth.simulateService WebDriver Bidi command

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/chengweih001/web-bluetooth/pull/655.html" title="Last updated on May 5, 2025, 9:55 PM UTC (d5ae371)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/655/89af1aa...chengweih001:d5ae371.html" title="Last updated on May 5, 2025, 9:55 PM UTC (d5ae371)">Diff</a>
> Complete the algorithm of bluetooth.simulateCharacteristic WebDriver Bidi command

- index.bs
This fix the [error](https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/14833916200/job/41641067859) in [chromium-bidi](https://github.com/GoogleChromeLabs/chromium-bidi), which is caused by:
```
error: parser errors
┌─ input:41:3
│
41 │   bluetooth.simulateCharacteristicResponse //
│   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing definition for rule bluetooth.simulateCharacteristicResponse
42 │   bluetooth.SimulateDescriptor //
43 │   bluetooth.simulateDescriptorResponse //
│   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing definition for rule bluetooth.simulateDescriptorResponse
Error: incremental parsing error
```
***
<a href="https://pr-preview.s3.amazonaws.com/chengweih001/web-bluetooth/pull/656.html" title="Last updated on May 5, 2025, 11:56 PM UTC …
> Fix BetoothCommand CDDL parsing error

- index.bs
Similar to the command BiDi modules export a CDDL with all the Events they have - https://w3c.github.io/webdriver-bidi/#module-contexts-events:~:text=BrowsingContextEvent%20%3D%20(
***
<a href="https://pr-preview.s3.amazonaws.com/Lightning00Blade/web-bluetooth/pull/653.html" title="Last updated on Apr 25, 2025, 3:11 PM UTC (2883df4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/653/d940d56...Lightning00Blade:2883df4.html" title="Last updated on Apr 25, 2025, 3:11 PM UTC (2883df4)">Diff</a>
> [WebDriver BiDi] Add CDDL for Events

- index.bs
Small fix for the CDDL, the last entry needs to not have `//`.
***
<a href="https://pr-preview.s3.amazonaws.com/Lightning00Blade/web-bluetooth/pull/658.html" title="Last updated on May 19, 2025, 9:31 AM UTC (e30df9d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/658/7127a3f...Lightning00Blade:e30df9d.html" title="Last updated on May 19, 2025, 9:31 AM UTC (e30df9d)">Diff</a>
> [WebDriver BiDi] Fix CDDL for events

- index.bs
Fix CDDL attributes. Analogous of https://github.com/w3c/webdriver-bidi/pull/927.
***
<a href="https://pr-preview.s3.amazonaws.com/sadym-chromium/web-bluetooth/pull/659.html" title="Last updated on Jun 24, 2025, 11:38 AM UTC (936bef3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/659/3517b6b...sadym-chromium:936bef3.html" title="Last updated on Jun 24, 2025, 11:38 AM UTC (936bef3)">Diff</a>
> Editorial: Adapt CDDL declarations to new version of Bikeshed

- index.bs
Complete the algorithms for `bluetooth.SimulateCharacteristicResponse` and `bluetooth.CharacteristicEventGenerated`.
***
<a href="https://pr-preview.s3.amazonaws.com/chengweih001/web-bluetooth/pull/661.html" title="Last updated on Aug 4, 2025, 9:15 PM UTC (e4af5af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/661/5508fa5...chengweih001:e4af5af.html" title="Last updated on Aug 4, 2025, 9:15 PM UTC (e4af5af)">Diff</a>
> Algorithms for bluetooth.characteristic commands
