index.html
And use those definitions in the rest of the spec.
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/create-devices/index.html.
=> Define how devices are represented at various levels

index.html
=> Remove the list of units.

use-cases.html
=> Changed the description of Web Bluetooth API to match Spec

index.html
@kenchris, how's this? Demo at https://rawgit.com/jyasskin/web-bluetooth-1/requestDevice-example/index.html#device-discovery
=> Add an example of how requestDevice() works.

index.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/97)
=> Add an example of using advertising data to read an iBeacon.

CONTRIBUTING.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/101)
=> Fix Web Bluetooth Community Group link.

index.html
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/capitalization/index.html.
@kenchris, does this cover everything you noticed?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/106)
=> All-caps acronyms except when they occur at the start of a name.

index.html
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/wording-cleanups/index.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/105)
=> Wording cleanups inspired by the contiguous IDL change

index.html
https://rawgit.com/jyasskin/web-bluetooth-1/partial-interfaces/index.html
@g-ortuno Does this fit in well with your implementation work?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/108)
=> Use partial interfaces to replace some `implements` statements.

index.html
@g-ortuno, does this fix #120?
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/permalinks/index.html
=> Add § links to the current section.

index.html
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/example-code/index.html#examples.
=> Add an introductory example, using the Heart Rate Service.

index.html
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/parent-order/index.html
=> Move the "parent" object to be the first member of each GATT type.

index.html
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/unify-tree-navigation/index.html.
The style is similar to https://streams.spec.whatwg.org/, but with named parameters and a little more formatting.
=> Unify the GATT tree navigation algorithms.

implementation-status.md
Hello @jyasskin,
As suggested in https://code.google.com/p/chromium/issues/detail?id=516608#c23, here's the start of a Hardware Compatibility List.
=> Add Hardware Compatibility List

index.bs, index.html
Demo at https://rawgit.com/jyasskin/web-bluetooth-1/active-notification-set/index.html.
@g-ortuno How's this?
=> Clarify how many active notification context sets there are.

README.md
=> Add README links to the test APIs and tests

tests/index.bs, tests/index.html
These were implemented in Chrome's testing library in https://codereview.chromium.org/1325953002/. Demo at https://rawgit.com/jyasskin/web-bluetooth-1/chooser-test-apis/tests/index.html.
=> Chooser test apis

implementation-status.md
=> Added ChromeOS udpates and fixed nits

index.bs, index.html
@g-ortuno https://rawgit.com/jyasskin/web-bluetooth-1/reject-empty-filters/index.html#dom-bluetooth-requestdevice
=> Block an empty list of filters.

index.bs, index.html
R=@jyasskin
Fix https://github.com/WebBluetoothCG/web-bluetooth/issues/189
=> Remove BluetoothDevice.paired

index.bs, index.html
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/gatt-server-connect/index.html
=> Fix #181: Unconditionally define device.gattServer, and connect from there.

index.bs, index.html
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/disconnect-on-gc/index.html.
=> Suggest UAs disconnect when a BluetoothDevice is gc'ed.

implementation-status.md
=> Add linux platform status

index.bs, index.html
Based on https://github.com/WebBluetoothCG/web-bluetooth/pull/217, I've also noticed another nit in the sample codes.
R=@jyasskin
=> Fixed example code nits

implementation-status.md
=> Remove Hardware Compatibility list

tests/index.html
Updated tests/index.html with latest version of bikeshed.
Preview at https://rawgit.com/WebBluetoothCG/web-bluetooth/32a5a4f365e3441e2a8f3ca0009f0f1b778a7bee/tests/index.html
tests/index.bs and tests.index.html were last [updated](https://github.com/WebBluetoothCG/web-bluetooth/commits/gh-pages/tests) together at #167.
=> Update tests/index.html using latest bikeshed.

tests/index.bs, tests/index.html
[Preview](https://rawgit.com/scheib/web-bluetooth/c19fd0432ee90430538e9bcf0741247a99c908fa/tests/index.html)
=> Mark testing document as out of date.

index.bs, index.html
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/update-permissions/index.html
=> Update the spec for changes in the Permissions spec.

implementation-status.md
@jyasskin Does that look good to you?
=> Add origin trial mention

index.bs, index.html
@tkybpp, please double-check that https://rawgit.com/jyasskin/web-bluetooth-1/jp-translation/index.html links to the right place. Thanks!
Fixes #259
=> Add a Japanese translation.

index.bs
Fixes #237.
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/jyasskin/web-bluetooth-1/raw/requestdevice-consider-connected/index.bs#scan-for-devices
@martijnthe, see if the wording looks right.
=> Include connected devices in scan results.

CONTRIBUTING.md
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/jyasskin/web-bluetooth-1/raw/block-blacklisted-gatt-children/index.bs#getgattchildren
Fixes #216.
=> Explain how to preview the built spec in CONTRIBUTING.md.

index.bs
Thanks for improving this, @domenic and @mikewest.
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/fix-global-object-links/index.bs.
=> Fix links to 'global object'.

index.bs
Preview: https://api.csswg.org/bikeshed/?url=https://github.com/jyasskin/web-bluetooth-1/raw/not-bonded/index.bs
=> Treat sites as not bonded to their devices.

index.bs
Ref. https://github.com/whatwg/html/issues/654
=> Editorial: Update spelling of HTML terms to en-US

index.bs
Fixes #284 
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/max-mtu/index.bs#dom-bluetoothremotegattserver-connect.
@beaufortfrancois @Vudentz
=> Specify that UAs should negotiate the MTU.

implementation-status.md
R: @jyasskin 
Source: https://codereview.chromium.org/2380843002/
=> Set "TypeError for bad UUIDs" to 55

implementation-status.md
I didn't break the Scanning API down into components yet.
@g-ortuno @beaufortfrancois
=> Record the Chrome implementation status of the whole GATT API.

implementation-status.md
=> Add Android Webview column

implementation-status.md
Background at  https://bugs.chromium.org/p/chromium/issues/detail?id=654687
=> Add "invalidate all objects when a device disconnects" row

implementation-status.md
=> Add GATT parallel operations note

index.bs
Preview at: https://api.csswg.org/bikeshed/?url=https://github.com/g-ortuno/web-bluetooth/raw/add-browsing-context-default/index.bs
=> Disambiguate links for browsing context

implementation-status.md
=> Update WIP features

use-cases.bs
Preview at: https://api.csswg.org/bikeshed/?url=https://github.com/g-ortuno/web-bluetooth/raw/add-repository-to-use-cases/use-cases.bs
=> Add Repository to use-cases so that Github is added to Issues section

.travis.yml
That way deploy.sh generates use-cases.html
=> Add use-cases to the list of specs.

implementation-status.md
Hey @cco3,
Can you review these changes and make sure I didn't forget anything?
=> Update Windows implementation

implementation-status.md
@scheib @beaufortfrancois 
Happy for me to add this narcissistic link?
=> Add Node.js port link

implementation-status.md
https://github.com/IjzerenHein/node-web-bluetooth
=> Added additional node-js port reference (node-web-bluetooth)

index.bs, scanning.bs
Explicitly link "resolve" to the promises guide.
=> Resolve ambiguous reference for "resolve"

index.bs
Found via https://github.com/tidoust/reffy-reports/issues/3#issuecomment-387550183
=> Remove default value for required dict member allowedDevices

index.bs
=> Fix bikeshed complaint

index.bs
At some examples, there are some variables to be declared by `let`, however they won't be changed later, just hope these may improve the spec :)
***
<a href="https://pr-preview.s3.amazonaws.com/yorkie/web-bluetooth/pull/458.html" title="Last updated on Oct 24, 2019, 1:50 PM UTC (4e724eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/458/cff3907...yorkie:4e724eb.html" title="Last updated on Oct 24, 2019, 1:50 PM UTC (4e724eb)">Diff</a>
=> `const` for the variables which are not to be re-assigned

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/web-bluetooth/pull/474.html" title="Last updated on Feb 13, 2020, 6:05 PM UTC (e0a7531)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/474/7610a77...odejesush:e0a7531.html" title="Last updated on Feb 13, 2020, 6:05 PM UTC (e0a7531)">Diff</a>
=> Add reillyeon and odejesush as Editors

scanning.bs
This fixes broken links and updates WebIDL to the new constructor syntax.
=> Fix Bikeshed errors in scanning.bs

scanning.bs
I'm pretty sure this is a typo but it needs confirmation
=> BluetoothServiceDataFilter instead of BluetoothManufacturerDataFilter ?

implementation-status.md
This change updates the implementation status for getAvailability().
=> Update status for getAvailability()

scanning.bs
Fix #521
[Bikeshed preview](https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/WebBluetoothCG/web-bluetooth/dcdff291c95b6185d25a5c56350984078ddd60a7/scanning.bs#dom-bluetooth-requestlescan)
=> Update scanning.bs : requestLEScan(options) specification issue

scanning.bs
Fix #519
[Bikeshed preview](https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/WebBluetoothCG/web-bluetooth/6756055a0a83840e5f7fc7b0d14a13cd4dd414df/scanning.bs#dom-bluetoothlescanfilter-bluetoothlescanfilter)
=> Update scanning.bs : BluetoothLEScanFilter(init) specification issue

data-filters-explainer.md
=> Add manufacturer data and service data filters explainer

index.bs
PTAL @reillyeon
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/web-bluetooth/pull/567.html" title="Last updated on Nov 15, 2021, 6:41 PM UTC (29697a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/567/c03dac5...miketaylr:29697a5.html" title="Last updated on Nov 15, 2021, 6:41 PM UTC (29697a5)">Diff</a>
=> Fix broken aborted dfn

index.bs
This PR addresses partially the bikeshed warning around Privacy and Security raised in https://github.com/WebBluetoothCG/web-bluetooth/issues/575 so that current PRs can be merged.
PTAL @reillyeon
***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/576.html" title="Last updated on Mar 7, 2022, 1:24 PM UTC (d812b6b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/576/b5f7617...d812b6b.html" title="Last updated on Mar 7, 2022, 1:24 PM UTC (d812b6b)">Diff</a>
=> Address partially bikeshed warning around Privacy and Security

implementation-status.md
Fix https://github.com/WebBluetoothCG/web-bluetooth/issues/580
=> Updated links to Firefox and Safari

implementation-status.md
https://developer.chrome.com/articles/bluetooth/#exclusion-filters
=> exclusionFilters shipped in Chrome 114
